/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConsultaCodigoRouteImport } from './routes/consulta-codigo'
import { Route as DevolucoesRouteImport } from './routes/devolucoes'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as HistoricoMaterialRouteImport } from './routes/historico-material'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NovaDevolucaoRouteImport } from './routes/nova-devolucao'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaCodigoRoute = ConsultaCodigoRouteImport.update({
  id: '/consulta-codigo',
  path: '/consulta-codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucoesRoute = DevolucoesRouteImport.update({
  id: '/devolucoes',
  path: '/devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoMaterialRoute = HistoricoMaterialRouteImport.update({
  id: '/historico-material',
  path: '/historico-material',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaDevolucaoRoute = NovaDevolucaoRouteImport.update({
  id: '/nova-devolucao',
  path: '/nova-devolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta-codigo': typeof ConsultaCodigoRoute
  '/devolucoes': typeof DevolucoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/historico-material': typeof HistoricoMaterialRoute
  '/login': typeof LoginRoute
  '/nova-devolucao': typeof NovaDevolucaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta-codigo': typeof ConsultaCodigoRoute
  '/devolucoes': typeof DevolucoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/historico-material': typeof HistoricoMaterialRoute
  '/login': typeof LoginRoute
  '/nova-devolucao': typeof NovaDevolucaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/consulta-codigo': typeof ConsultaCodigoRoute
  '/devolucoes': typeof DevolucoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/historico-material': typeof HistoricoMaterialRoute
  '/login': typeof LoginRoute
  '/nova-devolucao': typeof NovaDevolucaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/consulta-codigo'
    | '/devolucoes'
    | '/diagnostico'
    | '/historico-material'
    | '/login'
    | '/nova-devolucao'
    | '/relatorios'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/consulta-codigo'
    | '/devolucoes'
    | '/diagnostico'
    | '/historico-material'
    | '/login'
    | '/nova-devolucao'
    | '/relatorios'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/consulta-codigo'
    | '/devolucoes'
    | '/diagnostico'
    | '/historico-material'
    | '/login'
    | '/nova-devolucao'
    | '/relatorios'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConsultaCodigoRoute: typeof ConsultaCodigoRoute
  DevolucoesRoute: typeof DevolucoesRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  HistoricoMaterialRoute: typeof HistoricoMaterialRoute
  LoginRoute: typeof LoginRoute
  NovaDevolucaoRoute: typeof NovaDevolucaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta-codigo': {
      id: '/consulta-codigo'
      path: '/consulta-codigo'
      fullPath: '/consulta-codigo'
      preLoaderRoute: typeof ConsultaCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devolucoes': {
      id: '/devolucoes'
      path: '/devolucoes'
      fullPath: '/devolucoes'
      preLoaderRoute: typeof DevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-material': {
      id: '/historico-material'
      path: '/historico-material'
      fullPath: '/historico-material'
      preLoaderRoute: typeof HistoricoMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-devolucao': {
      id: '/nova-devolucao'
      path: '/nova-devolucao'
      fullPath: '/nova-devolucao'
      preLoaderRoute: typeof NovaDevolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConsultaCodigoRoute: ConsultaCodigoRoute,
  DevolucoesRoute: DevolucoesRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  HistoricoMaterialRoute: HistoricoMaterialRoute,
  LoginRoute: LoginRoute,
  NovaDevolucaoRoute: NovaDevolucaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
